// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AcctGroupsColumns holds the columns for the "acct_groups" table.
	AcctGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "nature", Type: field.TypeEnum, Enums: []string{"ASSET", "LIABILITY", "EQUITY", "INCOME", "EXPENSE"}},
		{Name: "is_system", Type: field.TypeBool, Default: false},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "acct_group_parent", Type: field.TypeInt, Nullable: true},
	}
	// AcctGroupsTable holds the schema information for the "acct_groups" table.
	AcctGroupsTable = &schema.Table{
		Name:       "acct_groups",
		Columns:    AcctGroupsColumns,
		PrimaryKey: []*schema.Column{AcctGroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "acct_groups_acct_groups_parent",
				Columns:    []*schema.Column{AcctGroupsColumns[6]},
				RefColumns: []*schema.Column{AcctGroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "acct_group_code",
				Unique:  true,
				Columns: []*schema.Column{AcctGroupsColumns[1]},
			},
			{
				Name:    "acct_group_name",
				Unique:  false,
				Columns: []*schema.Column{AcctGroupsColumns[2]},
			},
			{
				Name:    "acct_group_nature",
				Unique:  false,
				Columns: []*schema.Column{AcctGroupsColumns[3]},
			},
		},
	}
	// CountriesColumns holds the columns for the "countries" table.
	CountriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 10},
	}
	// CountriesTable holds the schema information for the "countries" table.
	CountriesTable = &schema.Table{
		Name:       "countries",
		Columns:    CountriesColumns,
		PrimaryKey: []*schema.Column{CountriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "country_name",
				Unique:  true,
				Columns: []*schema.Column{CountriesColumns[1]},
			},
			{
				Name:    "country_code",
				Unique:  true,
				Columns: []*schema.Column{CountriesColumns[2]},
			},
		},
	}
	// JournalsColumns holds the columns for the "journals" table.
	JournalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeInt8, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "date", Type: field.TypeTime},
		{Name: "voucher_type", Type: field.TypeString},
		{Name: "voucher_no", Type: field.TypeString},
		{Name: "voucher_date", Type: field.TypeTime},
		{Name: "reference_no", Type: field.TypeString, Nullable: true},
		{Name: "external_ref", Type: field.TypeString, Nullable: true},
		{Name: "journal_status", Type: field.TypeEnum, Enums: []string{"DRAFT", "APPROVED", "POSTED", "CANCELLED"}, Default: "DRAFT"},
		{Name: "approved_by", Type: field.TypeInt, Nullable: true},
		{Name: "financial_year_id", Type: field.TypeInt, Nullable: true},
		{Name: "narration", Type: field.TypeString, Nullable: true},
		{Name: "source_module", Type: field.TypeString, Nullable: true},
		{Name: "source_type", Type: field.TypeString, Nullable: true},
		{Name: "source_id", Type: field.TypeInt, Nullable: true},
		{Name: "total_debit", Type: field.TypeFloat64, Default: 0},
		{Name: "total_credit", Type: field.TypeFloat64, Default: 0},
	}
	// JournalsTable holds the schema information for the "journals" table.
	JournalsTable = &schema.Table{
		Name:       "journals",
		Columns:    JournalsColumns,
		PrimaryKey: []*schema.Column{JournalsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "journal_date",
				Unique:  false,
				Columns: []*schema.Column{JournalsColumns[4]},
			},
			{
				Name:    "journal_voucher_type",
				Unique:  false,
				Columns: []*schema.Column{JournalsColumns[5]},
			},
			{
				Name:    "journal_voucher_no",
				Unique:  true,
				Columns: []*schema.Column{JournalsColumns[6]},
			},
			{
				Name:    "journal_status",
				Unique:  false,
				Columns: []*schema.Column{JournalsColumns[1]},
			},
			{
				Name:    "journal_date_voucher_type",
				Unique:  false,
				Columns: []*schema.Column{JournalsColumns[4], JournalsColumns[5]},
			},
		},
	}
	// JournalLinesColumns holds the columns for the "journal_lines" table.
	JournalLinesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeInt8, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "debit", Type: field.TypeFloat64, Default: 0},
		{Name: "credit", Type: field.TypeFloat64, Default: 0},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "reference_type", Type: field.TypeString, Nullable: true},
		{Name: "reference_id", Type: field.TypeInt, Nullable: true},
		{Name: "line_no", Type: field.TypeInt, Default: 1},
		{Name: "journal_id", Type: field.TypeInt},
		{Name: "ledger_id", Type: field.TypeInt},
	}
	// JournalLinesTable holds the schema information for the "journal_lines" table.
	JournalLinesTable = &schema.Table{
		Name:       "journal_lines",
		Columns:    JournalLinesColumns,
		PrimaryKey: []*schema.Column{JournalLinesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "journal_lines_journals_lines",
				Columns:    []*schema.Column{JournalLinesColumns[10]},
				RefColumns: []*schema.Column{JournalsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "journal_lines_ledgers_journal_lines",
				Columns:    []*schema.Column{JournalLinesColumns[11]},
				RefColumns: []*schema.Column{LedgersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "journal_line_journal_id",
				Unique:  false,
				Columns: []*schema.Column{JournalLinesColumns[10]},
			},
			{
				Name:    "journal_line_ledger_id",
				Unique:  false,
				Columns: []*schema.Column{JournalLinesColumns[11]},
			},
			{
				Name:    "journal_line_journal_id_ledger_id",
				Unique:  false,
				Columns: []*schema.Column{JournalLinesColumns[10], JournalLinesColumns[11]},
			},
		},
	}
	// LedgersColumns holds the columns for the "ledgers" table.
	LedgersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeInt8, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "balance", Type: field.TypeFloat64, Default: 0},
		{Name: "acct_group_ledgers", Type: field.TypeInt, Nullable: true},
		{Name: "group_id", Type: field.TypeInt},
	}
	// LedgersTable holds the schema information for the "ledgers" table.
	LedgersTable = &schema.Table{
		Name:       "ledgers",
		Columns:    LedgersColumns,
		PrimaryKey: []*schema.Column{LedgersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ledgers_acct_groups_ledgers",
				Columns:    []*schema.Column{LedgersColumns[8]},
				RefColumns: []*schema.Column{AcctGroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "ledgers_acct_groups_group",
				Columns:    []*schema.Column{LedgersColumns[9]},
				RefColumns: []*schema.Column{AcctGroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "ledger_code",
				Unique:  true,
				Columns: []*schema.Column{LedgersColumns[4]},
			},
			{
				Name:    "ledger_name",
				Unique:  false,
				Columns: []*schema.Column{LedgersColumns[5]},
			},
			{
				Name:    "ledger_group_id",
				Unique:  false,
				Columns: []*schema.Column{LedgersColumns[9]},
			},
			{
				Name:    "ledger_group_id_name",
				Unique:  false,
				Columns: []*schema.Column{LedgersColumns[9], LedgersColumns[5]},
			},
		},
	}
	// PartyMasterColumns holds the columns for the "party_master" table.
	PartyMasterColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeInt8, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"CUSTOMER", "SUPPLIER", "BOTH"}},
		{Name: "display_name", Type: field.TypeString},
		{Name: "legal_name", Type: field.TypeString, Nullable: true},
		{Name: "gst_no", Type: field.TypeString, Nullable: true},
		{Name: "pan_no", Type: field.TypeString, Nullable: true},
		{Name: "contact_person", Type: field.TypeString, Nullable: true},
		{Name: "mobile", Type: field.TypeString, Nullable: true},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "website", Type: field.TypeString, Nullable: true},
		{Name: "credit_limit", Type: field.TypeFloat64, Default: 0},
		{Name: "credit_days", Type: field.TypeInt, Default: 0},
		{Name: "opening_balance", Type: field.TypeFloat64, Default: 0},
		{Name: "address", Type: field.TypeString, Nullable: true},
		{Name: "city", Type: field.TypeString, Nullable: true},
		{Name: "state", Type: field.TypeString, Nullable: true},
		{Name: "country", Type: field.TypeString, Default: "India"},
		{Name: "pincode", Type: field.TypeString, Nullable: true},
		{Name: "ledger_id", Type: field.TypeInt, Unique: true},
	}
	// PartyMasterTable holds the schema information for the "party_master" table.
	PartyMasterTable = &schema.Table{
		Name:       "party_master",
		Columns:    PartyMasterColumns,
		PrimaryKey: []*schema.Column{PartyMasterColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "party_master_ledgers_party",
				Columns:    []*schema.Column{PartyMasterColumns[22]},
				RefColumns: []*schema.Column{LedgersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "partymaster_ledger_id",
				Unique:  true,
				Columns: []*schema.Column{PartyMasterColumns[22]},
			},
			{
				Name:    "partymaster_type",
				Unique:  false,
				Columns: []*schema.Column{PartyMasterColumns[4]},
			},
			{
				Name:    "partymaster_gst_no",
				Unique:  false,
				Columns: []*schema.Column{PartyMasterColumns[7]},
			},
			{
				Name:    "partymaster_mobile",
				Unique:  false,
				Columns: []*schema.Column{PartyMasterColumns[10]},
			},
			{
				Name:    "partymaster_email",
				Unique:  false,
				Columns: []*schema.Column{PartyMasterColumns[12]},
			},
			{
				Name:    "partymaster_display_name",
				Unique:  false,
				Columns: []*schema.Column{PartyMasterColumns[5]},
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString, Default: ""},
		{Name: "label", Type: field.TypeString, Default: ""},
		{Name: "group", Type: field.TypeString, Default: "general"},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "setting_key",
				Unique:  true,
				Columns: []*schema.Column{SettingsColumns[1]},
			},
		},
	}
	// StatesColumns holds the columns for the "states" table.
	StatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "code", Type: field.TypeString, Nullable: true, Size: 10},
		{Name: "gst_code", Type: field.TypeString, Nullable: true, Size: 5},
		{Name: "country_id", Type: field.TypeInt},
	}
	// StatesTable holds the schema information for the "states" table.
	StatesTable = &schema.Table{
		Name:       "states",
		Columns:    StatesColumns,
		PrimaryKey: []*schema.Column{StatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "states_countries_states",
				Columns:    []*schema.Column{StatesColumns[4]},
				RefColumns: []*schema.Column{CountriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "state_country_id",
				Unique:  false,
				Columns: []*schema.Column{StatesColumns[4]},
			},
			{
				Name:    "state_country_id_name",
				Unique:  true,
				Columns: []*schema.Column{StatesColumns[4], StatesColumns[1]},
			},
			{
				Name:    "state_gst_code",
				Unique:  false,
				Columns: []*schema.Column{StatesColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AcctGroupsTable,
		CountriesTable,
		JournalsTable,
		JournalLinesTable,
		LedgersTable,
		PartyMasterTable,
		SettingsTable,
		StatesTable,
	}
)

func init() {
	AcctGroupsTable.ForeignKeys[0].RefTable = AcctGroupsTable
	JournalLinesTable.ForeignKeys[0].RefTable = JournalsTable
	JournalLinesTable.ForeignKeys[1].RefTable = LedgersTable
	LedgersTable.ForeignKeys[0].RefTable = AcctGroupsTable
	LedgersTable.ForeignKeys[1].RefTable = AcctGroupsTable
	PartyMasterTable.ForeignKeys[0].RefTable = LedgersTable
	PartyMasterTable.Annotation = &entsql.Annotation{
		Table: "party_master",
	}
	StatesTable.ForeignKeys[0].RefTable = CountriesTable
}
