// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/subhasundardas/gofar/ent/acct_group"
)

// Acct_Group is the model entity for the Acct_Group schema.
type Acct_Group struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Nature holds the value of the "nature" field.
	Nature acct_group.Nature `json:"nature,omitempty"`
	// IsSystem holds the value of the "is_system" field.
	IsSystem bool `json:"is_system,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the Acct_GroupQuery when eager-loading is set.
	Edges             Acct_GroupEdges `json:"edges"`
	acct_group_parent *int
	selectValues      sql.SelectValues
}

// Acct_GroupEdges holds the relations/edges for other nodes in the graph.
type Acct_GroupEdges struct {
	// Children holds the value of the children edge.
	Children []*Acct_Group `json:"children,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *Acct_Group `json:"parent,omitempty"`
	// Ledgers holds the value of the ledgers edge.
	Ledgers []*Ledger `json:"ledgers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e Acct_GroupEdges) ChildrenOrErr() ([]*Acct_Group, error) {
	if e.loadedTypes[0] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Acct_GroupEdges) ParentOrErr() (*Acct_Group, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: acct_group.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// LedgersOrErr returns the Ledgers value or an error if the edge
// was not loaded in eager-loading.
func (e Acct_GroupEdges) LedgersOrErr() ([]*Ledger, error) {
	if e.loadedTypes[2] {
		return e.Ledgers, nil
	}
	return nil, &NotLoadedError{edge: "ledgers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Acct_Group) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case acct_group.FieldIsSystem:
			values[i] = new(sql.NullBool)
		case acct_group.FieldID:
			values[i] = new(sql.NullInt64)
		case acct_group.FieldCode, acct_group.FieldName, acct_group.FieldNature, acct_group.FieldDescription:
			values[i] = new(sql.NullString)
		case acct_group.ForeignKeys[0]: // acct_group_parent
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Acct_Group fields.
func (_m *Acct_Group) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case acct_group.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case acct_group.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case acct_group.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case acct_group.FieldNature:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nature", values[i])
			} else if value.Valid {
				_m.Nature = acct_group.Nature(value.String)
			}
		case acct_group.FieldIsSystem:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_system", values[i])
			} else if value.Valid {
				_m.IsSystem = value.Bool
			}
		case acct_group.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case acct_group.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field acct_group_parent", value)
			} else if value.Valid {
				_m.acct_group_parent = new(int)
				*_m.acct_group_parent = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Acct_Group.
// This includes values selected through modifiers, order, etc.
func (_m *Acct_Group) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChildren queries the "children" edge of the Acct_Group entity.
func (_m *Acct_Group) QueryChildren() *AcctGroupQuery {
	return NewAcctGroupClient(_m.config).QueryChildren(_m)
}

// QueryParent queries the "parent" edge of the Acct_Group entity.
func (_m *Acct_Group) QueryParent() *AcctGroupQuery {
	return NewAcctGroupClient(_m.config).QueryParent(_m)
}

// QueryLedgers queries the "ledgers" edge of the Acct_Group entity.
func (_m *Acct_Group) QueryLedgers() *LedgerQuery {
	return NewAcctGroupClient(_m.config).QueryLedgers(_m)
}

// Update returns a builder for updating this Acct_Group.
// Note that you need to call Acct_Group.Unwrap() before calling this method if this Acct_Group
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Acct_Group) Update() *AcctGroupUpdateOne {
	return NewAcctGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Acct_Group entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Acct_Group) Unwrap() *Acct_Group {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Acct_Group is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Acct_Group) String() string {
	var builder strings.Builder
	builder.WriteString("Acct_Group(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("nature=")
	builder.WriteString(fmt.Sprintf("%v", _m.Nature))
	builder.WriteString(", ")
	builder.WriteString("is_system=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSystem))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteByte(')')
	return builder.String()
}

// Acct_Groups is a parsable slice of Acct_Group.
type Acct_Groups []*Acct_Group
