// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/subhasundardas/gofar/ent/acct_group"
	"github.com/subhasundardas/gofar/ent/ledger"
	"github.com/subhasundardas/gofar/ent/predicate"
)

// AcctGroupUpdate is the builder for updating Acct_Group entities.
type AcctGroupUpdate struct {
	config
	hooks    []Hook
	mutation *AcctGroupMutation
}

// Where appends a list predicates to the AcctGroupUpdate builder.
func (_u *AcctGroupUpdate) Where(ps ...predicate.Acct_Group) *AcctGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *AcctGroupUpdate) SetCode(v string) *AcctGroupUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *AcctGroupUpdate) SetNillableCode(v *string) *AcctGroupUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AcctGroupUpdate) SetName(v string) *AcctGroupUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AcctGroupUpdate) SetNillableName(v *string) *AcctGroupUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNature sets the "nature" field.
func (_u *AcctGroupUpdate) SetNature(v acct_group.Nature) *AcctGroupUpdate {
	_u.mutation.SetNature(v)
	return _u
}

// SetNillableNature sets the "nature" field if the given value is not nil.
func (_u *AcctGroupUpdate) SetNillableNature(v *acct_group.Nature) *AcctGroupUpdate {
	if v != nil {
		_u.SetNature(*v)
	}
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *AcctGroupUpdate) SetIsSystem(v bool) *AcctGroupUpdate {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *AcctGroupUpdate) SetNillableIsSystem(v *bool) *AcctGroupUpdate {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AcctGroupUpdate) SetDescription(v string) *AcctGroupUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AcctGroupUpdate) SetNillableDescription(v *string) *AcctGroupUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AcctGroupUpdate) ClearDescription() *AcctGroupUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// AddChildIDs adds the "children" edge to the Acct_Group entity by IDs.
func (_u *AcctGroupUpdate) AddChildIDs(ids ...int) *AcctGroupUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Acct_Group entity.
func (_u *AcctGroupUpdate) AddChildren(v ...*Acct_Group) *AcctGroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetParentID sets the "parent" edge to the Acct_Group entity by ID.
func (_u *AcctGroupUpdate) SetParentID(id int) *AcctGroupUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Acct_Group entity by ID if the given value is not nil.
func (_u *AcctGroupUpdate) SetNillableParentID(id *int) *AcctGroupUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Acct_Group entity.
func (_u *AcctGroupUpdate) SetParent(v *Acct_Group) *AcctGroupUpdate {
	return _u.SetParentID(v.ID)
}

// AddLedgerIDs adds the "ledgers" edge to the Ledger entity by IDs.
func (_u *AcctGroupUpdate) AddLedgerIDs(ids ...int) *AcctGroupUpdate {
	_u.mutation.AddLedgerIDs(ids...)
	return _u
}

// AddLedgers adds the "ledgers" edges to the Ledger entity.
func (_u *AcctGroupUpdate) AddLedgers(v ...*Ledger) *AcctGroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLedgerIDs(ids...)
}

// Mutation returns the AcctGroupMutation object of the builder.
func (_u *AcctGroupUpdate) Mutation() *AcctGroupMutation {
	return _u.mutation
}

// ClearChildren clears all "children" edges to the Acct_Group entity.
func (_u *AcctGroupUpdate) ClearChildren() *AcctGroupUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Acct_Group entities by IDs.
func (_u *AcctGroupUpdate) RemoveChildIDs(ids ...int) *AcctGroupUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Acct_Group entities.
func (_u *AcctGroupUpdate) RemoveChildren(v ...*Acct_Group) *AcctGroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearParent clears the "parent" edge to the Acct_Group entity.
func (_u *AcctGroupUpdate) ClearParent() *AcctGroupUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearLedgers clears all "ledgers" edges to the Ledger entity.
func (_u *AcctGroupUpdate) ClearLedgers() *AcctGroupUpdate {
	_u.mutation.ClearLedgers()
	return _u
}

// RemoveLedgerIDs removes the "ledgers" edge to Ledger entities by IDs.
func (_u *AcctGroupUpdate) RemoveLedgerIDs(ids ...int) *AcctGroupUpdate {
	_u.mutation.RemoveLedgerIDs(ids...)
	return _u
}

// RemoveLedgers removes "ledgers" edges to Ledger entities.
func (_u *AcctGroupUpdate) RemoveLedgers(v ...*Ledger) *AcctGroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLedgerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AcctGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AcctGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AcctGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AcctGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AcctGroupUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := acct_group.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Acct_Group.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := acct_group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Acct_Group.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nature(); ok {
		if err := acct_group.NatureValidator(v); err != nil {
			return &ValidationError{Name: "nature", err: fmt.Errorf(`ent: validator failed for field "Acct_Group.nature": %w`, err)}
		}
	}
	return nil
}

func (_u *AcctGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(acct_group.Table, acct_group.Columns, sqlgraph.NewFieldSpec(acct_group.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(acct_group.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(acct_group.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nature(); ok {
		_spec.SetField(acct_group.FieldNature, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(acct_group.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(acct_group.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(acct_group.FieldDescription, field.TypeString)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   acct_group.ChildrenTable,
			Columns: []string{acct_group.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(acct_group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   acct_group.ChildrenTable,
			Columns: []string{acct_group.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(acct_group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   acct_group.ChildrenTable,
			Columns: []string{acct_group.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(acct_group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   acct_group.ParentTable,
			Columns: []string{acct_group.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(acct_group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   acct_group.ParentTable,
			Columns: []string{acct_group.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(acct_group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   acct_group.LedgersTable,
			Columns: []string{acct_group.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLedgersIDs(); len(nodes) > 0 && !_u.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   acct_group.LedgersTable,
			Columns: []string{acct_group.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   acct_group.LedgersTable,
			Columns: []string{acct_group.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{acct_group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AcctGroupUpdateOne is the builder for updating a single Acct_Group entity.
type AcctGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AcctGroupMutation
}

// SetCode sets the "code" field.
func (_u *AcctGroupUpdateOne) SetCode(v string) *AcctGroupUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *AcctGroupUpdateOne) SetNillableCode(v *string) *AcctGroupUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AcctGroupUpdateOne) SetName(v string) *AcctGroupUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AcctGroupUpdateOne) SetNillableName(v *string) *AcctGroupUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNature sets the "nature" field.
func (_u *AcctGroupUpdateOne) SetNature(v acct_group.Nature) *AcctGroupUpdateOne {
	_u.mutation.SetNature(v)
	return _u
}

// SetNillableNature sets the "nature" field if the given value is not nil.
func (_u *AcctGroupUpdateOne) SetNillableNature(v *acct_group.Nature) *AcctGroupUpdateOne {
	if v != nil {
		_u.SetNature(*v)
	}
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *AcctGroupUpdateOne) SetIsSystem(v bool) *AcctGroupUpdateOne {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *AcctGroupUpdateOne) SetNillableIsSystem(v *bool) *AcctGroupUpdateOne {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AcctGroupUpdateOne) SetDescription(v string) *AcctGroupUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AcctGroupUpdateOne) SetNillableDescription(v *string) *AcctGroupUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AcctGroupUpdateOne) ClearDescription() *AcctGroupUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// AddChildIDs adds the "children" edge to the Acct_Group entity by IDs.
func (_u *AcctGroupUpdateOne) AddChildIDs(ids ...int) *AcctGroupUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Acct_Group entity.
func (_u *AcctGroupUpdateOne) AddChildren(v ...*Acct_Group) *AcctGroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetParentID sets the "parent" edge to the Acct_Group entity by ID.
func (_u *AcctGroupUpdateOne) SetParentID(id int) *AcctGroupUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Acct_Group entity by ID if the given value is not nil.
func (_u *AcctGroupUpdateOne) SetNillableParentID(id *int) *AcctGroupUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Acct_Group entity.
func (_u *AcctGroupUpdateOne) SetParent(v *Acct_Group) *AcctGroupUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddLedgerIDs adds the "ledgers" edge to the Ledger entity by IDs.
func (_u *AcctGroupUpdateOne) AddLedgerIDs(ids ...int) *AcctGroupUpdateOne {
	_u.mutation.AddLedgerIDs(ids...)
	return _u
}

// AddLedgers adds the "ledgers" edges to the Ledger entity.
func (_u *AcctGroupUpdateOne) AddLedgers(v ...*Ledger) *AcctGroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLedgerIDs(ids...)
}

// Mutation returns the AcctGroupMutation object of the builder.
func (_u *AcctGroupUpdateOne) Mutation() *AcctGroupMutation {
	return _u.mutation
}

// ClearChildren clears all "children" edges to the Acct_Group entity.
func (_u *AcctGroupUpdateOne) ClearChildren() *AcctGroupUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Acct_Group entities by IDs.
func (_u *AcctGroupUpdateOne) RemoveChildIDs(ids ...int) *AcctGroupUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Acct_Group entities.
func (_u *AcctGroupUpdateOne) RemoveChildren(v ...*Acct_Group) *AcctGroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearParent clears the "parent" edge to the Acct_Group entity.
func (_u *AcctGroupUpdateOne) ClearParent() *AcctGroupUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearLedgers clears all "ledgers" edges to the Ledger entity.
func (_u *AcctGroupUpdateOne) ClearLedgers() *AcctGroupUpdateOne {
	_u.mutation.ClearLedgers()
	return _u
}

// RemoveLedgerIDs removes the "ledgers" edge to Ledger entities by IDs.
func (_u *AcctGroupUpdateOne) RemoveLedgerIDs(ids ...int) *AcctGroupUpdateOne {
	_u.mutation.RemoveLedgerIDs(ids...)
	return _u
}

// RemoveLedgers removes "ledgers" edges to Ledger entities.
func (_u *AcctGroupUpdateOne) RemoveLedgers(v ...*Ledger) *AcctGroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLedgerIDs(ids...)
}

// Where appends a list predicates to the AcctGroupUpdate builder.
func (_u *AcctGroupUpdateOne) Where(ps ...predicate.Acct_Group) *AcctGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AcctGroupUpdateOne) Select(field string, fields ...string) *AcctGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Acct_Group entity.
func (_u *AcctGroupUpdateOne) Save(ctx context.Context) (*Acct_Group, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AcctGroupUpdateOne) SaveX(ctx context.Context) *Acct_Group {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AcctGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AcctGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AcctGroupUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := acct_group.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Acct_Group.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := acct_group.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Acct_Group.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nature(); ok {
		if err := acct_group.NatureValidator(v); err != nil {
			return &ValidationError{Name: "nature", err: fmt.Errorf(`ent: validator failed for field "Acct_Group.nature": %w`, err)}
		}
	}
	return nil
}

func (_u *AcctGroupUpdateOne) sqlSave(ctx context.Context) (_node *Acct_Group, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(acct_group.Table, acct_group.Columns, sqlgraph.NewFieldSpec(acct_group.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Acct_Group.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, acct_group.FieldID)
		for _, f := range fields {
			if !acct_group.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != acct_group.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(acct_group.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(acct_group.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nature(); ok {
		_spec.SetField(acct_group.FieldNature, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(acct_group.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(acct_group.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(acct_group.FieldDescription, field.TypeString)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   acct_group.ChildrenTable,
			Columns: []string{acct_group.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(acct_group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   acct_group.ChildrenTable,
			Columns: []string{acct_group.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(acct_group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   acct_group.ChildrenTable,
			Columns: []string{acct_group.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(acct_group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   acct_group.ParentTable,
			Columns: []string{acct_group.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(acct_group.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   acct_group.ParentTable,
			Columns: []string{acct_group.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(acct_group.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   acct_group.LedgersTable,
			Columns: []string{acct_group.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLedgersIDs(); len(nodes) > 0 && !_u.mutation.LedgersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   acct_group.LedgersTable,
			Columns: []string{acct_group.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   acct_group.LedgersTable,
			Columns: []string{acct_group.LedgersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Acct_Group{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{acct_group.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
