// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/subhasundardas/gofar/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/subhasundardas/gofar/ent/acct_group"
	"github.com/subhasundardas/gofar/ent/country"
	"github.com/subhasundardas/gofar/ent/journal"
	"github.com/subhasundardas/gofar/ent/journal_line"
	"github.com/subhasundardas/gofar/ent/ledger"
	"github.com/subhasundardas/gofar/ent/partymaster"
	"github.com/subhasundardas/gofar/ent/setting"
	"github.com/subhasundardas/gofar/ent/state"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Acct_Group is the client for interacting with the Acct_Group builders.
	Acct_Group *AcctGroupClient
	// Country is the client for interacting with the Country builders.
	Country *CountryClient
	// Journal is the client for interacting with the Journal builders.
	Journal *JournalClient
	// Journal_Line is the client for interacting with the Journal_Line builders.
	Journal_Line *JournalLineClient
	// Ledger is the client for interacting with the Ledger builders.
	Ledger *LedgerClient
	// PartyMaster is the client for interacting with the PartyMaster builders.
	PartyMaster *PartyMasterClient
	// Setting is the client for interacting with the Setting builders.
	Setting *SettingClient
	// State is the client for interacting with the State builders.
	State *StateClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Acct_Group = NewAcctGroupClient(c.config)
	c.Country = NewCountryClient(c.config)
	c.Journal = NewJournalClient(c.config)
	c.Journal_Line = NewJournalLineClient(c.config)
	c.Ledger = NewLedgerClient(c.config)
	c.PartyMaster = NewPartyMasterClient(c.config)
	c.Setting = NewSettingClient(c.config)
	c.State = NewStateClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		Acct_Group:   NewAcctGroupClient(cfg),
		Country:      NewCountryClient(cfg),
		Journal:      NewJournalClient(cfg),
		Journal_Line: NewJournalLineClient(cfg),
		Ledger:       NewLedgerClient(cfg),
		PartyMaster:  NewPartyMasterClient(cfg),
		Setting:      NewSettingClient(cfg),
		State:        NewStateClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		Acct_Group:   NewAcctGroupClient(cfg),
		Country:      NewCountryClient(cfg),
		Journal:      NewJournalClient(cfg),
		Journal_Line: NewJournalLineClient(cfg),
		Ledger:       NewLedgerClient(cfg),
		PartyMaster:  NewPartyMasterClient(cfg),
		Setting:      NewSettingClient(cfg),
		State:        NewStateClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Acct_Group.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Acct_Group, c.Country, c.Journal, c.Journal_Line, c.Ledger, c.PartyMaster,
		c.Setting, c.State,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Acct_Group, c.Country, c.Journal, c.Journal_Line, c.Ledger, c.PartyMaster,
		c.Setting, c.State,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AcctGroupMutation:
		return c.Acct_Group.mutate(ctx, m)
	case *CountryMutation:
		return c.Country.mutate(ctx, m)
	case *JournalMutation:
		return c.Journal.mutate(ctx, m)
	case *JournalLineMutation:
		return c.Journal_Line.mutate(ctx, m)
	case *LedgerMutation:
		return c.Ledger.mutate(ctx, m)
	case *PartyMasterMutation:
		return c.PartyMaster.mutate(ctx, m)
	case *SettingMutation:
		return c.Setting.mutate(ctx, m)
	case *StateMutation:
		return c.State.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AcctGroupClient is a client for the Acct_Group schema.
type AcctGroupClient struct {
	config
}

// NewAcctGroupClient returns a client for the Acct_Group from the given config.
func NewAcctGroupClient(c config) *AcctGroupClient {
	return &AcctGroupClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `acct_group.Hooks(f(g(h())))`.
func (c *AcctGroupClient) Use(hooks ...Hook) {
	c.hooks.Acct_Group = append(c.hooks.Acct_Group, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `acct_group.Intercept(f(g(h())))`.
func (c *AcctGroupClient) Intercept(interceptors ...Interceptor) {
	c.inters.Acct_Group = append(c.inters.Acct_Group, interceptors...)
}

// Create returns a builder for creating a Acct_Group entity.
func (c *AcctGroupClient) Create() *AcctGroupCreate {
	mutation := newAcctGroupMutation(c.config, OpCreate)
	return &AcctGroupCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Acct_Group entities.
func (c *AcctGroupClient) CreateBulk(builders ...*AcctGroupCreate) *AcctGroupCreateBulk {
	return &AcctGroupCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AcctGroupClient) MapCreateBulk(slice any, setFunc func(*AcctGroupCreate, int)) *AcctGroupCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AcctGroupCreateBulk{err: fmt.Errorf("calling to AcctGroupClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AcctGroupCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AcctGroupCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Acct_Group.
func (c *AcctGroupClient) Update() *AcctGroupUpdate {
	mutation := newAcctGroupMutation(c.config, OpUpdate)
	return &AcctGroupUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AcctGroupClient) UpdateOne(_m *Acct_Group) *AcctGroupUpdateOne {
	mutation := newAcctGroupMutation(c.config, OpUpdateOne, withAcct_Group(_m))
	return &AcctGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AcctGroupClient) UpdateOneID(id int) *AcctGroupUpdateOne {
	mutation := newAcctGroupMutation(c.config, OpUpdateOne, withAcct_GroupID(id))
	return &AcctGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Acct_Group.
func (c *AcctGroupClient) Delete() *AcctGroupDelete {
	mutation := newAcctGroupMutation(c.config, OpDelete)
	return &AcctGroupDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AcctGroupClient) DeleteOne(_m *Acct_Group) *AcctGroupDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AcctGroupClient) DeleteOneID(id int) *AcctGroupDeleteOne {
	builder := c.Delete().Where(acct_group.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AcctGroupDeleteOne{builder}
}

// Query returns a query builder for Acct_Group.
func (c *AcctGroupClient) Query() *AcctGroupQuery {
	return &AcctGroupQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAcctGroup},
		inters: c.Interceptors(),
	}
}

// Get returns a Acct_Group entity by its id.
func (c *AcctGroupClient) Get(ctx context.Context, id int) (*Acct_Group, error) {
	return c.Query().Where(acct_group.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AcctGroupClient) GetX(ctx context.Context, id int) *Acct_Group {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChildren queries the children edge of a Acct_Group.
func (c *AcctGroupClient) QueryChildren(_m *Acct_Group) *AcctGroupQuery {
	query := (&AcctGroupClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(acct_group.Table, acct_group.FieldID, id),
			sqlgraph.To(acct_group.Table, acct_group.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, acct_group.ChildrenTable, acct_group.ChildrenColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryParent queries the parent edge of a Acct_Group.
func (c *AcctGroupClient) QueryParent(_m *Acct_Group) *AcctGroupQuery {
	query := (&AcctGroupClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(acct_group.Table, acct_group.FieldID, id),
			sqlgraph.To(acct_group.Table, acct_group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, acct_group.ParentTable, acct_group.ParentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLedgers queries the ledgers edge of a Acct_Group.
func (c *AcctGroupClient) QueryLedgers(_m *Acct_Group) *LedgerQuery {
	query := (&LedgerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(acct_group.Table, acct_group.FieldID, id),
			sqlgraph.To(ledger.Table, ledger.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, acct_group.LedgersTable, acct_group.LedgersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AcctGroupClient) Hooks() []Hook {
	return c.hooks.Acct_Group
}

// Interceptors returns the client interceptors.
func (c *AcctGroupClient) Interceptors() []Interceptor {
	return c.inters.Acct_Group
}

func (c *AcctGroupClient) mutate(ctx context.Context, m *AcctGroupMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AcctGroupCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AcctGroupUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AcctGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AcctGroupDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Acct_Group mutation op: %q", m.Op())
	}
}

// CountryClient is a client for the Country schema.
type CountryClient struct {
	config
}

// NewCountryClient returns a client for the Country from the given config.
func NewCountryClient(c config) *CountryClient {
	return &CountryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `country.Hooks(f(g(h())))`.
func (c *CountryClient) Use(hooks ...Hook) {
	c.hooks.Country = append(c.hooks.Country, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `country.Intercept(f(g(h())))`.
func (c *CountryClient) Intercept(interceptors ...Interceptor) {
	c.inters.Country = append(c.inters.Country, interceptors...)
}

// Create returns a builder for creating a Country entity.
func (c *CountryClient) Create() *CountryCreate {
	mutation := newCountryMutation(c.config, OpCreate)
	return &CountryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Country entities.
func (c *CountryClient) CreateBulk(builders ...*CountryCreate) *CountryCreateBulk {
	return &CountryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CountryClient) MapCreateBulk(slice any, setFunc func(*CountryCreate, int)) *CountryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CountryCreateBulk{err: fmt.Errorf("calling to CountryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CountryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CountryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Country.
func (c *CountryClient) Update() *CountryUpdate {
	mutation := newCountryMutation(c.config, OpUpdate)
	return &CountryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CountryClient) UpdateOne(_m *Country) *CountryUpdateOne {
	mutation := newCountryMutation(c.config, OpUpdateOne, withCountry(_m))
	return &CountryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CountryClient) UpdateOneID(id int) *CountryUpdateOne {
	mutation := newCountryMutation(c.config, OpUpdateOne, withCountryID(id))
	return &CountryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Country.
func (c *CountryClient) Delete() *CountryDelete {
	mutation := newCountryMutation(c.config, OpDelete)
	return &CountryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CountryClient) DeleteOne(_m *Country) *CountryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CountryClient) DeleteOneID(id int) *CountryDeleteOne {
	builder := c.Delete().Where(country.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CountryDeleteOne{builder}
}

// Query returns a query builder for Country.
func (c *CountryClient) Query() *CountryQuery {
	return &CountryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCountry},
		inters: c.Interceptors(),
	}
}

// Get returns a Country entity by its id.
func (c *CountryClient) Get(ctx context.Context, id int) (*Country, error) {
	return c.Query().Where(country.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CountryClient) GetX(ctx context.Context, id int) *Country {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryStates queries the states edge of a Country.
func (c *CountryClient) QueryStates(_m *Country) *StateQuery {
	query := (&StateClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(country.Table, country.FieldID, id),
			sqlgraph.To(state.Table, state.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, country.StatesTable, country.StatesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CountryClient) Hooks() []Hook {
	return c.hooks.Country
}

// Interceptors returns the client interceptors.
func (c *CountryClient) Interceptors() []Interceptor {
	return c.inters.Country
}

func (c *CountryClient) mutate(ctx context.Context, m *CountryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CountryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CountryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CountryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CountryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Country mutation op: %q", m.Op())
	}
}

// JournalClient is a client for the Journal schema.
type JournalClient struct {
	config
}

// NewJournalClient returns a client for the Journal from the given config.
func NewJournalClient(c config) *JournalClient {
	return &JournalClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `journal.Hooks(f(g(h())))`.
func (c *JournalClient) Use(hooks ...Hook) {
	c.hooks.Journal = append(c.hooks.Journal, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `journal.Intercept(f(g(h())))`.
func (c *JournalClient) Intercept(interceptors ...Interceptor) {
	c.inters.Journal = append(c.inters.Journal, interceptors...)
}

// Create returns a builder for creating a Journal entity.
func (c *JournalClient) Create() *JournalCreate {
	mutation := newJournalMutation(c.config, OpCreate)
	return &JournalCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Journal entities.
func (c *JournalClient) CreateBulk(builders ...*JournalCreate) *JournalCreateBulk {
	return &JournalCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *JournalClient) MapCreateBulk(slice any, setFunc func(*JournalCreate, int)) *JournalCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &JournalCreateBulk{err: fmt.Errorf("calling to JournalClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*JournalCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &JournalCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Journal.
func (c *JournalClient) Update() *JournalUpdate {
	mutation := newJournalMutation(c.config, OpUpdate)
	return &JournalUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *JournalClient) UpdateOne(_m *Journal) *JournalUpdateOne {
	mutation := newJournalMutation(c.config, OpUpdateOne, withJournal(_m))
	return &JournalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *JournalClient) UpdateOneID(id int) *JournalUpdateOne {
	mutation := newJournalMutation(c.config, OpUpdateOne, withJournalID(id))
	return &JournalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Journal.
func (c *JournalClient) Delete() *JournalDelete {
	mutation := newJournalMutation(c.config, OpDelete)
	return &JournalDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *JournalClient) DeleteOne(_m *Journal) *JournalDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *JournalClient) DeleteOneID(id int) *JournalDeleteOne {
	builder := c.Delete().Where(journal.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &JournalDeleteOne{builder}
}

// Query returns a query builder for Journal.
func (c *JournalClient) Query() *JournalQuery {
	return &JournalQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeJournal},
		inters: c.Interceptors(),
	}
}

// Get returns a Journal entity by its id.
func (c *JournalClient) Get(ctx context.Context, id int) (*Journal, error) {
	return c.Query().Where(journal.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *JournalClient) GetX(ctx context.Context, id int) *Journal {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLines queries the lines edge of a Journal.
func (c *JournalClient) QueryLines(_m *Journal) *JournalLineQuery {
	query := (&JournalLineClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(journal.Table, journal.FieldID, id),
			sqlgraph.To(journal_line.Table, journal_line.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, journal.LinesTable, journal.LinesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *JournalClient) Hooks() []Hook {
	return c.hooks.Journal
}

// Interceptors returns the client interceptors.
func (c *JournalClient) Interceptors() []Interceptor {
	return c.inters.Journal
}

func (c *JournalClient) mutate(ctx context.Context, m *JournalMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&JournalCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&JournalUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&JournalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&JournalDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Journal mutation op: %q", m.Op())
	}
}

// JournalLineClient is a client for the Journal_Line schema.
type JournalLineClient struct {
	config
}

// NewJournalLineClient returns a client for the Journal_Line from the given config.
func NewJournalLineClient(c config) *JournalLineClient {
	return &JournalLineClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `journal_line.Hooks(f(g(h())))`.
func (c *JournalLineClient) Use(hooks ...Hook) {
	c.hooks.Journal_Line = append(c.hooks.Journal_Line, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `journal_line.Intercept(f(g(h())))`.
func (c *JournalLineClient) Intercept(interceptors ...Interceptor) {
	c.inters.Journal_Line = append(c.inters.Journal_Line, interceptors...)
}

// Create returns a builder for creating a Journal_Line entity.
func (c *JournalLineClient) Create() *JournalLineCreate {
	mutation := newJournalLineMutation(c.config, OpCreate)
	return &JournalLineCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Journal_Line entities.
func (c *JournalLineClient) CreateBulk(builders ...*JournalLineCreate) *JournalLineCreateBulk {
	return &JournalLineCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *JournalLineClient) MapCreateBulk(slice any, setFunc func(*JournalLineCreate, int)) *JournalLineCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &JournalLineCreateBulk{err: fmt.Errorf("calling to JournalLineClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*JournalLineCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &JournalLineCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Journal_Line.
func (c *JournalLineClient) Update() *JournalLineUpdate {
	mutation := newJournalLineMutation(c.config, OpUpdate)
	return &JournalLineUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *JournalLineClient) UpdateOne(_m *Journal_Line) *JournalLineUpdateOne {
	mutation := newJournalLineMutation(c.config, OpUpdateOne, withJournal_Line(_m))
	return &JournalLineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *JournalLineClient) UpdateOneID(id int) *JournalLineUpdateOne {
	mutation := newJournalLineMutation(c.config, OpUpdateOne, withJournal_LineID(id))
	return &JournalLineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Journal_Line.
func (c *JournalLineClient) Delete() *JournalLineDelete {
	mutation := newJournalLineMutation(c.config, OpDelete)
	return &JournalLineDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *JournalLineClient) DeleteOne(_m *Journal_Line) *JournalLineDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *JournalLineClient) DeleteOneID(id int) *JournalLineDeleteOne {
	builder := c.Delete().Where(journal_line.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &JournalLineDeleteOne{builder}
}

// Query returns a query builder for Journal_Line.
func (c *JournalLineClient) Query() *JournalLineQuery {
	return &JournalLineQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeJournalLine},
		inters: c.Interceptors(),
	}
}

// Get returns a Journal_Line entity by its id.
func (c *JournalLineClient) Get(ctx context.Context, id int) (*Journal_Line, error) {
	return c.Query().Where(journal_line.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *JournalLineClient) GetX(ctx context.Context, id int) *Journal_Line {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryJournal queries the journal edge of a Journal_Line.
func (c *JournalLineClient) QueryJournal(_m *Journal_Line) *JournalQuery {
	query := (&JournalClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(journal_line.Table, journal_line.FieldID, id),
			sqlgraph.To(journal.Table, journal.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, journal_line.JournalTable, journal_line.JournalColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLedger queries the ledger edge of a Journal_Line.
func (c *JournalLineClient) QueryLedger(_m *Journal_Line) *LedgerQuery {
	query := (&LedgerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(journal_line.Table, journal_line.FieldID, id),
			sqlgraph.To(ledger.Table, ledger.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, journal_line.LedgerTable, journal_line.LedgerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *JournalLineClient) Hooks() []Hook {
	return c.hooks.Journal_Line
}

// Interceptors returns the client interceptors.
func (c *JournalLineClient) Interceptors() []Interceptor {
	return c.inters.Journal_Line
}

func (c *JournalLineClient) mutate(ctx context.Context, m *JournalLineMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&JournalLineCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&JournalLineUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&JournalLineUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&JournalLineDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Journal_Line mutation op: %q", m.Op())
	}
}

// LedgerClient is a client for the Ledger schema.
type LedgerClient struct {
	config
}

// NewLedgerClient returns a client for the Ledger from the given config.
func NewLedgerClient(c config) *LedgerClient {
	return &LedgerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ledger.Hooks(f(g(h())))`.
func (c *LedgerClient) Use(hooks ...Hook) {
	c.hooks.Ledger = append(c.hooks.Ledger, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ledger.Intercept(f(g(h())))`.
func (c *LedgerClient) Intercept(interceptors ...Interceptor) {
	c.inters.Ledger = append(c.inters.Ledger, interceptors...)
}

// Create returns a builder for creating a Ledger entity.
func (c *LedgerClient) Create() *LedgerCreate {
	mutation := newLedgerMutation(c.config, OpCreate)
	return &LedgerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Ledger entities.
func (c *LedgerClient) CreateBulk(builders ...*LedgerCreate) *LedgerCreateBulk {
	return &LedgerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LedgerClient) MapCreateBulk(slice any, setFunc func(*LedgerCreate, int)) *LedgerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LedgerCreateBulk{err: fmt.Errorf("calling to LedgerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LedgerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LedgerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Ledger.
func (c *LedgerClient) Update() *LedgerUpdate {
	mutation := newLedgerMutation(c.config, OpUpdate)
	return &LedgerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LedgerClient) UpdateOne(_m *Ledger) *LedgerUpdateOne {
	mutation := newLedgerMutation(c.config, OpUpdateOne, withLedger(_m))
	return &LedgerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LedgerClient) UpdateOneID(id int) *LedgerUpdateOne {
	mutation := newLedgerMutation(c.config, OpUpdateOne, withLedgerID(id))
	return &LedgerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Ledger.
func (c *LedgerClient) Delete() *LedgerDelete {
	mutation := newLedgerMutation(c.config, OpDelete)
	return &LedgerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LedgerClient) DeleteOne(_m *Ledger) *LedgerDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LedgerClient) DeleteOneID(id int) *LedgerDeleteOne {
	builder := c.Delete().Where(ledger.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LedgerDeleteOne{builder}
}

// Query returns a query builder for Ledger.
func (c *LedgerClient) Query() *LedgerQuery {
	return &LedgerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLedger},
		inters: c.Interceptors(),
	}
}

// Get returns a Ledger entity by its id.
func (c *LedgerClient) Get(ctx context.Context, id int) (*Ledger, error) {
	return c.Query().Where(ledger.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LedgerClient) GetX(ctx context.Context, id int) *Ledger {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryGroup queries the group edge of a Ledger.
func (c *LedgerClient) QueryGroup(_m *Ledger) *AcctGroupQuery {
	query := (&AcctGroupClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ledger.Table, ledger.FieldID, id),
			sqlgraph.To(acct_group.Table, acct_group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ledger.GroupTable, ledger.GroupColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryParty queries the party edge of a Ledger.
func (c *LedgerClient) QueryParty(_m *Ledger) *PartyMasterQuery {
	query := (&PartyMasterClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ledger.Table, ledger.FieldID, id),
			sqlgraph.To(partymaster.Table, partymaster.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ledger.PartyTable, ledger.PartyColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *LedgerClient) Hooks() []Hook {
	return c.hooks.Ledger
}

// Interceptors returns the client interceptors.
func (c *LedgerClient) Interceptors() []Interceptor {
	return c.inters.Ledger
}

func (c *LedgerClient) mutate(ctx context.Context, m *LedgerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LedgerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LedgerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LedgerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LedgerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Ledger mutation op: %q", m.Op())
	}
}

// PartyMasterClient is a client for the PartyMaster schema.
type PartyMasterClient struct {
	config
}

// NewPartyMasterClient returns a client for the PartyMaster from the given config.
func NewPartyMasterClient(c config) *PartyMasterClient {
	return &PartyMasterClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `partymaster.Hooks(f(g(h())))`.
func (c *PartyMasterClient) Use(hooks ...Hook) {
	c.hooks.PartyMaster = append(c.hooks.PartyMaster, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `partymaster.Intercept(f(g(h())))`.
func (c *PartyMasterClient) Intercept(interceptors ...Interceptor) {
	c.inters.PartyMaster = append(c.inters.PartyMaster, interceptors...)
}

// Create returns a builder for creating a PartyMaster entity.
func (c *PartyMasterClient) Create() *PartyMasterCreate {
	mutation := newPartyMasterMutation(c.config, OpCreate)
	return &PartyMasterCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PartyMaster entities.
func (c *PartyMasterClient) CreateBulk(builders ...*PartyMasterCreate) *PartyMasterCreateBulk {
	return &PartyMasterCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PartyMasterClient) MapCreateBulk(slice any, setFunc func(*PartyMasterCreate, int)) *PartyMasterCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PartyMasterCreateBulk{err: fmt.Errorf("calling to PartyMasterClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PartyMasterCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PartyMasterCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PartyMaster.
func (c *PartyMasterClient) Update() *PartyMasterUpdate {
	mutation := newPartyMasterMutation(c.config, OpUpdate)
	return &PartyMasterUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PartyMasterClient) UpdateOne(_m *PartyMaster) *PartyMasterUpdateOne {
	mutation := newPartyMasterMutation(c.config, OpUpdateOne, withPartyMaster(_m))
	return &PartyMasterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PartyMasterClient) UpdateOneID(id int) *PartyMasterUpdateOne {
	mutation := newPartyMasterMutation(c.config, OpUpdateOne, withPartyMasterID(id))
	return &PartyMasterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PartyMaster.
func (c *PartyMasterClient) Delete() *PartyMasterDelete {
	mutation := newPartyMasterMutation(c.config, OpDelete)
	return &PartyMasterDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PartyMasterClient) DeleteOne(_m *PartyMaster) *PartyMasterDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PartyMasterClient) DeleteOneID(id int) *PartyMasterDeleteOne {
	builder := c.Delete().Where(partymaster.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PartyMasterDeleteOne{builder}
}

// Query returns a query builder for PartyMaster.
func (c *PartyMasterClient) Query() *PartyMasterQuery {
	return &PartyMasterQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePartyMaster},
		inters: c.Interceptors(),
	}
}

// Get returns a PartyMaster entity by its id.
func (c *PartyMasterClient) Get(ctx context.Context, id int) (*PartyMaster, error) {
	return c.Query().Where(partymaster.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PartyMasterClient) GetX(ctx context.Context, id int) *PartyMaster {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLedger queries the ledger edge of a PartyMaster.
func (c *PartyMasterClient) QueryLedger(_m *PartyMaster) *LedgerQuery {
	query := (&LedgerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(partymaster.Table, partymaster.FieldID, id),
			sqlgraph.To(ledger.Table, ledger.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, partymaster.LedgerTable, partymaster.LedgerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PartyMasterClient) Hooks() []Hook {
	return c.hooks.PartyMaster
}

// Interceptors returns the client interceptors.
func (c *PartyMasterClient) Interceptors() []Interceptor {
	return c.inters.PartyMaster
}

func (c *PartyMasterClient) mutate(ctx context.Context, m *PartyMasterMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PartyMasterCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PartyMasterUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PartyMasterUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PartyMasterDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PartyMaster mutation op: %q", m.Op())
	}
}

// SettingClient is a client for the Setting schema.
type SettingClient struct {
	config
}

// NewSettingClient returns a client for the Setting from the given config.
func NewSettingClient(c config) *SettingClient {
	return &SettingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `setting.Hooks(f(g(h())))`.
func (c *SettingClient) Use(hooks ...Hook) {
	c.hooks.Setting = append(c.hooks.Setting, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `setting.Intercept(f(g(h())))`.
func (c *SettingClient) Intercept(interceptors ...Interceptor) {
	c.inters.Setting = append(c.inters.Setting, interceptors...)
}

// Create returns a builder for creating a Setting entity.
func (c *SettingClient) Create() *SettingCreate {
	mutation := newSettingMutation(c.config, OpCreate)
	return &SettingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Setting entities.
func (c *SettingClient) CreateBulk(builders ...*SettingCreate) *SettingCreateBulk {
	return &SettingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SettingClient) MapCreateBulk(slice any, setFunc func(*SettingCreate, int)) *SettingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SettingCreateBulk{err: fmt.Errorf("calling to SettingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SettingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SettingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Setting.
func (c *SettingClient) Update() *SettingUpdate {
	mutation := newSettingMutation(c.config, OpUpdate)
	return &SettingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SettingClient) UpdateOne(_m *Setting) *SettingUpdateOne {
	mutation := newSettingMutation(c.config, OpUpdateOne, withSetting(_m))
	return &SettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SettingClient) UpdateOneID(id int) *SettingUpdateOne {
	mutation := newSettingMutation(c.config, OpUpdateOne, withSettingID(id))
	return &SettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Setting.
func (c *SettingClient) Delete() *SettingDelete {
	mutation := newSettingMutation(c.config, OpDelete)
	return &SettingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SettingClient) DeleteOne(_m *Setting) *SettingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SettingClient) DeleteOneID(id int) *SettingDeleteOne {
	builder := c.Delete().Where(setting.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SettingDeleteOne{builder}
}

// Query returns a query builder for Setting.
func (c *SettingClient) Query() *SettingQuery {
	return &SettingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSetting},
		inters: c.Interceptors(),
	}
}

// Get returns a Setting entity by its id.
func (c *SettingClient) Get(ctx context.Context, id int) (*Setting, error) {
	return c.Query().Where(setting.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SettingClient) GetX(ctx context.Context, id int) *Setting {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SettingClient) Hooks() []Hook {
	return c.hooks.Setting
}

// Interceptors returns the client interceptors.
func (c *SettingClient) Interceptors() []Interceptor {
	return c.inters.Setting
}

func (c *SettingClient) mutate(ctx context.Context, m *SettingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SettingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SettingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SettingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Setting mutation op: %q", m.Op())
	}
}

// StateClient is a client for the State schema.
type StateClient struct {
	config
}

// NewStateClient returns a client for the State from the given config.
func NewStateClient(c config) *StateClient {
	return &StateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `state.Hooks(f(g(h())))`.
func (c *StateClient) Use(hooks ...Hook) {
	c.hooks.State = append(c.hooks.State, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `state.Intercept(f(g(h())))`.
func (c *StateClient) Intercept(interceptors ...Interceptor) {
	c.inters.State = append(c.inters.State, interceptors...)
}

// Create returns a builder for creating a State entity.
func (c *StateClient) Create() *StateCreate {
	mutation := newStateMutation(c.config, OpCreate)
	return &StateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of State entities.
func (c *StateClient) CreateBulk(builders ...*StateCreate) *StateCreateBulk {
	return &StateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StateClient) MapCreateBulk(slice any, setFunc func(*StateCreate, int)) *StateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StateCreateBulk{err: fmt.Errorf("calling to StateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for State.
func (c *StateClient) Update() *StateUpdate {
	mutation := newStateMutation(c.config, OpUpdate)
	return &StateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StateClient) UpdateOne(_m *State) *StateUpdateOne {
	mutation := newStateMutation(c.config, OpUpdateOne, withState(_m))
	return &StateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StateClient) UpdateOneID(id int) *StateUpdateOne {
	mutation := newStateMutation(c.config, OpUpdateOne, withStateID(id))
	return &StateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for State.
func (c *StateClient) Delete() *StateDelete {
	mutation := newStateMutation(c.config, OpDelete)
	return &StateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StateClient) DeleteOne(_m *State) *StateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StateClient) DeleteOneID(id int) *StateDeleteOne {
	builder := c.Delete().Where(state.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StateDeleteOne{builder}
}

// Query returns a query builder for State.
func (c *StateClient) Query() *StateQuery {
	return &StateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeState},
		inters: c.Interceptors(),
	}
}

// Get returns a State entity by its id.
func (c *StateClient) Get(ctx context.Context, id int) (*State, error) {
	return c.Query().Where(state.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StateClient) GetX(ctx context.Context, id int) *State {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCountry queries the country edge of a State.
func (c *StateClient) QueryCountry(_m *State) *CountryQuery {
	query := (&CountryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(state.Table, state.FieldID, id),
			sqlgraph.To(country.Table, country.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, state.CountryTable, state.CountryColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StateClient) Hooks() []Hook {
	return c.hooks.State
}

// Interceptors returns the client interceptors.
func (c *StateClient) Interceptors() []Interceptor {
	return c.inters.State
}

func (c *StateClient) mutate(ctx context.Context, m *StateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown State mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Acct_Group, Country, Journal, Journal_Line, Ledger, PartyMaster, Setting,
		State []ent.Hook
	}
	inters struct {
		Acct_Group, Country, Journal, Journal_Line, Ledger, PartyMaster, Setting,
		State []ent.Interceptor
	}
)
