// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/subhasundardas/gofar/ent/journal"
	"github.com/subhasundardas/gofar/ent/journal_line"
	"github.com/subhasundardas/gofar/ent/ledger"
)

// JournalLineCreate is the builder for creating a Journal_Line entity.
type JournalLineCreate struct {
	config
	mutation *JournalLineMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *JournalLineCreate) SetStatus(v int8) *JournalLineCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *JournalLineCreate) SetNillableStatus(v *int8) *JournalLineCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *JournalLineCreate) SetCreatedAt(v time.Time) *JournalLineCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *JournalLineCreate) SetNillableCreatedAt(v *time.Time) *JournalLineCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *JournalLineCreate) SetUpdatedAt(v time.Time) *JournalLineCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *JournalLineCreate) SetNillableUpdatedAt(v *time.Time) *JournalLineCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetJournalID sets the "journal_id" field.
func (_c *JournalLineCreate) SetJournalID(v int) *JournalLineCreate {
	_c.mutation.SetJournalID(v)
	return _c
}

// SetLedgerID sets the "ledger_id" field.
func (_c *JournalLineCreate) SetLedgerID(v int) *JournalLineCreate {
	_c.mutation.SetLedgerID(v)
	return _c
}

// SetDebit sets the "debit" field.
func (_c *JournalLineCreate) SetDebit(v float64) *JournalLineCreate {
	_c.mutation.SetDebit(v)
	return _c
}

// SetNillableDebit sets the "debit" field if the given value is not nil.
func (_c *JournalLineCreate) SetNillableDebit(v *float64) *JournalLineCreate {
	if v != nil {
		_c.SetDebit(*v)
	}
	return _c
}

// SetCredit sets the "credit" field.
func (_c *JournalLineCreate) SetCredit(v float64) *JournalLineCreate {
	_c.mutation.SetCredit(v)
	return _c
}

// SetNillableCredit sets the "credit" field if the given value is not nil.
func (_c *JournalLineCreate) SetNillableCredit(v *float64) *JournalLineCreate {
	if v != nil {
		_c.SetCredit(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *JournalLineCreate) SetDescription(v string) *JournalLineCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *JournalLineCreate) SetNillableDescription(v *string) *JournalLineCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetReferenceType sets the "reference_type" field.
func (_c *JournalLineCreate) SetReferenceType(v string) *JournalLineCreate {
	_c.mutation.SetReferenceType(v)
	return _c
}

// SetNillableReferenceType sets the "reference_type" field if the given value is not nil.
func (_c *JournalLineCreate) SetNillableReferenceType(v *string) *JournalLineCreate {
	if v != nil {
		_c.SetReferenceType(*v)
	}
	return _c
}

// SetReferenceID sets the "reference_id" field.
func (_c *JournalLineCreate) SetReferenceID(v int) *JournalLineCreate {
	_c.mutation.SetReferenceID(v)
	return _c
}

// SetNillableReferenceID sets the "reference_id" field if the given value is not nil.
func (_c *JournalLineCreate) SetNillableReferenceID(v *int) *JournalLineCreate {
	if v != nil {
		_c.SetReferenceID(*v)
	}
	return _c
}

// SetLineNo sets the "line_no" field.
func (_c *JournalLineCreate) SetLineNo(v int) *JournalLineCreate {
	_c.mutation.SetLineNo(v)
	return _c
}

// SetNillableLineNo sets the "line_no" field if the given value is not nil.
func (_c *JournalLineCreate) SetNillableLineNo(v *int) *JournalLineCreate {
	if v != nil {
		_c.SetLineNo(*v)
	}
	return _c
}

// SetJournal sets the "journal" edge to the Journal entity.
func (_c *JournalLineCreate) SetJournal(v *Journal) *JournalLineCreate {
	return _c.SetJournalID(v.ID)
}

// SetLedger sets the "ledger" edge to the Ledger entity.
func (_c *JournalLineCreate) SetLedger(v *Ledger) *JournalLineCreate {
	return _c.SetLedgerID(v.ID)
}

// Mutation returns the JournalLineMutation object of the builder.
func (_c *JournalLineCreate) Mutation() *JournalLineMutation {
	return _c.mutation
}

// Save creates the Journal_Line in the database.
func (_c *JournalLineCreate) Save(ctx context.Context) (*Journal_Line, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *JournalLineCreate) SaveX(ctx context.Context) *Journal_Line {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JournalLineCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JournalLineCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *JournalLineCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := journal_line.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := journal_line.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := journal_line.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Debit(); !ok {
		v := journal_line.DefaultDebit
		_c.mutation.SetDebit(v)
	}
	if _, ok := _c.mutation.Credit(); !ok {
		v := journal_line.DefaultCredit
		_c.mutation.SetCredit(v)
	}
	if _, ok := _c.mutation.LineNo(); !ok {
		v := journal_line.DefaultLineNo
		_c.mutation.SetLineNo(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *JournalLineCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Journal_Line.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Journal_Line.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Journal_Line.updated_at"`)}
	}
	if _, ok := _c.mutation.JournalID(); !ok {
		return &ValidationError{Name: "journal_id", err: errors.New(`ent: missing required field "Journal_Line.journal_id"`)}
	}
	if _, ok := _c.mutation.LedgerID(); !ok {
		return &ValidationError{Name: "ledger_id", err: errors.New(`ent: missing required field "Journal_Line.ledger_id"`)}
	}
	if _, ok := _c.mutation.Debit(); !ok {
		return &ValidationError{Name: "debit", err: errors.New(`ent: missing required field "Journal_Line.debit"`)}
	}
	if _, ok := _c.mutation.Credit(); !ok {
		return &ValidationError{Name: "credit", err: errors.New(`ent: missing required field "Journal_Line.credit"`)}
	}
	if _, ok := _c.mutation.LineNo(); !ok {
		return &ValidationError{Name: "line_no", err: errors.New(`ent: missing required field "Journal_Line.line_no"`)}
	}
	if len(_c.mutation.JournalIDs()) == 0 {
		return &ValidationError{Name: "journal", err: errors.New(`ent: missing required edge "Journal_Line.journal"`)}
	}
	if len(_c.mutation.LedgerIDs()) == 0 {
		return &ValidationError{Name: "ledger", err: errors.New(`ent: missing required edge "Journal_Line.ledger"`)}
	}
	return nil
}

func (_c *JournalLineCreate) sqlSave(ctx context.Context) (*Journal_Line, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *JournalLineCreate) createSpec() (*Journal_Line, *sqlgraph.CreateSpec) {
	var (
		_node = &Journal_Line{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(journal_line.Table, sqlgraph.NewFieldSpec(journal_line.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(journal_line.FieldStatus, field.TypeInt8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(journal_line.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(journal_line.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Debit(); ok {
		_spec.SetField(journal_line.FieldDebit, field.TypeFloat64, value)
		_node.Debit = value
	}
	if value, ok := _c.mutation.Credit(); ok {
		_spec.SetField(journal_line.FieldCredit, field.TypeFloat64, value)
		_node.Credit = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(journal_line.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.ReferenceType(); ok {
		_spec.SetField(journal_line.FieldReferenceType, field.TypeString, value)
		_node.ReferenceType = &value
	}
	if value, ok := _c.mutation.ReferenceID(); ok {
		_spec.SetField(journal_line.FieldReferenceID, field.TypeInt, value)
		_node.ReferenceID = &value
	}
	if value, ok := _c.mutation.LineNo(); ok {
		_spec.SetField(journal_line.FieldLineNo, field.TypeInt, value)
		_node.LineNo = value
	}
	if nodes := _c.mutation.JournalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   journal_line.JournalTable,
			Columns: []string{journal_line.JournalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journal.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.JournalID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LedgerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   journal_line.LedgerTable,
			Columns: []string{journal_line.LedgerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledger.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LedgerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// JournalLineCreateBulk is the builder for creating many Journal_Line entities in bulk.
type JournalLineCreateBulk struct {
	config
	err      error
	builders []*JournalLineCreate
}

// Save creates the Journal_Line entities in the database.
func (_c *JournalLineCreateBulk) Save(ctx context.Context) ([]*Journal_Line, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Journal_Line, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JournalLineMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *JournalLineCreateBulk) SaveX(ctx context.Context) []*Journal_Line {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JournalLineCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JournalLineCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
