// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/subhasundardas/gofar/ent/acct_group"
	"github.com/subhasundardas/gofar/ent/country"
	"github.com/subhasundardas/gofar/ent/journal"
	"github.com/subhasundardas/gofar/ent/journal_line"
	"github.com/subhasundardas/gofar/ent/ledger"
	"github.com/subhasundardas/gofar/ent/partymaster"
	"github.com/subhasundardas/gofar/ent/schema"
	"github.com/subhasundardas/gofar/ent/setting"
	"github.com/subhasundardas/gofar/ent/state"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	acct_groupFields := schema.Acct_Group{}.Fields()
	_ = acct_groupFields
	// acct_groupDescCode is the schema descriptor for code field.
	acct_groupDescCode := acct_groupFields[0].Descriptor()
	// acct_group.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	acct_group.CodeValidator = acct_groupDescCode.Validators[0].(func(string) error)
	// acct_groupDescName is the schema descriptor for name field.
	acct_groupDescName := acct_groupFields[1].Descriptor()
	// acct_group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	acct_group.NameValidator = func() func(string) error {
		validators := acct_groupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// acct_groupDescIsSystem is the schema descriptor for is_system field.
	acct_groupDescIsSystem := acct_groupFields[3].Descriptor()
	// acct_group.DefaultIsSystem holds the default value on creation for the is_system field.
	acct_group.DefaultIsSystem = acct_groupDescIsSystem.Default.(bool)
	// acct_groupDescDescription is the schema descriptor for description field.
	acct_groupDescDescription := acct_groupFields[4].Descriptor()
	// acct_group.DefaultDescription holds the default value on creation for the description field.
	acct_group.DefaultDescription = acct_groupDescDescription.Default.(string)
	countryFields := schema.Country{}.Fields()
	_ = countryFields
	// countryDescName is the schema descriptor for name field.
	countryDescName := countryFields[0].Descriptor()
	// country.NameValidator is a validator for the "name" field. It is called by the builders before save.
	country.NameValidator = func() func(string) error {
		validators := countryDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// countryDescCode is the schema descriptor for code field.
	countryDescCode := countryFields[1].Descriptor()
	// country.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	country.CodeValidator = func() func(string) error {
		validators := countryDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	journalMixin := schema.Journal{}.Mixin()
	journalMixinFields0 := journalMixin[0].Fields()
	_ = journalMixinFields0
	journalFields := schema.Journal{}.Fields()
	_ = journalFields
	// journalDescStatus is the schema descriptor for status field.
	journalDescStatus := journalMixinFields0[0].Descriptor()
	// journal.DefaultStatus holds the default value on creation for the status field.
	journal.DefaultStatus = journalDescStatus.Default.(int8)
	// journalDescCreatedAt is the schema descriptor for created_at field.
	journalDescCreatedAt := journalMixinFields0[1].Descriptor()
	// journal.DefaultCreatedAt holds the default value on creation for the created_at field.
	journal.DefaultCreatedAt = journalDescCreatedAt.Default.(func() time.Time)
	// journalDescUpdatedAt is the schema descriptor for updated_at field.
	journalDescUpdatedAt := journalMixinFields0[2].Descriptor()
	// journal.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	journal.DefaultUpdatedAt = journalDescUpdatedAt.Default.(func() time.Time)
	// journal.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	journal.UpdateDefaultUpdatedAt = journalDescUpdatedAt.UpdateDefault.(func() time.Time)
	// journalDescVoucherType is the schema descriptor for voucher_type field.
	journalDescVoucherType := journalFields[1].Descriptor()
	// journal.VoucherTypeValidator is a validator for the "voucher_type" field. It is called by the builders before save.
	journal.VoucherTypeValidator = journalDescVoucherType.Validators[0].(func(string) error)
	// journalDescVoucherNo is the schema descriptor for voucher_no field.
	journalDescVoucherNo := journalFields[2].Descriptor()
	// journal.VoucherNoValidator is a validator for the "voucher_no" field. It is called by the builders before save.
	journal.VoucherNoValidator = journalDescVoucherNo.Validators[0].(func(string) error)
	// journalDescTotalDebit is the schema descriptor for total_debit field.
	journalDescTotalDebit := journalFields[13].Descriptor()
	// journal.DefaultTotalDebit holds the default value on creation for the total_debit field.
	journal.DefaultTotalDebit = journalDescTotalDebit.Default.(float64)
	// journalDescTotalCredit is the schema descriptor for total_credit field.
	journalDescTotalCredit := journalFields[14].Descriptor()
	// journal.DefaultTotalCredit holds the default value on creation for the total_credit field.
	journal.DefaultTotalCredit = journalDescTotalCredit.Default.(float64)
	journal_lineMixin := schema.Journal_Line{}.Mixin()
	journal_lineMixinFields0 := journal_lineMixin[0].Fields()
	_ = journal_lineMixinFields0
	journal_lineFields := schema.Journal_Line{}.Fields()
	_ = journal_lineFields
	// journal_lineDescStatus is the schema descriptor for status field.
	journal_lineDescStatus := journal_lineMixinFields0[0].Descriptor()
	// journal_line.DefaultStatus holds the default value on creation for the status field.
	journal_line.DefaultStatus = journal_lineDescStatus.Default.(int8)
	// journal_lineDescCreatedAt is the schema descriptor for created_at field.
	journal_lineDescCreatedAt := journal_lineMixinFields0[1].Descriptor()
	// journal_line.DefaultCreatedAt holds the default value on creation for the created_at field.
	journal_line.DefaultCreatedAt = journal_lineDescCreatedAt.Default.(func() time.Time)
	// journal_lineDescUpdatedAt is the schema descriptor for updated_at field.
	journal_lineDescUpdatedAt := journal_lineMixinFields0[2].Descriptor()
	// journal_line.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	journal_line.DefaultUpdatedAt = journal_lineDescUpdatedAt.Default.(func() time.Time)
	// journal_line.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	journal_line.UpdateDefaultUpdatedAt = journal_lineDescUpdatedAt.UpdateDefault.(func() time.Time)
	// journal_lineDescDebit is the schema descriptor for debit field.
	journal_lineDescDebit := journal_lineFields[2].Descriptor()
	// journal_line.DefaultDebit holds the default value on creation for the debit field.
	journal_line.DefaultDebit = journal_lineDescDebit.Default.(float64)
	// journal_lineDescCredit is the schema descriptor for credit field.
	journal_lineDescCredit := journal_lineFields[3].Descriptor()
	// journal_line.DefaultCredit holds the default value on creation for the credit field.
	journal_line.DefaultCredit = journal_lineDescCredit.Default.(float64)
	// journal_lineDescLineNo is the schema descriptor for line_no field.
	journal_lineDescLineNo := journal_lineFields[7].Descriptor()
	// journal_line.DefaultLineNo holds the default value on creation for the line_no field.
	journal_line.DefaultLineNo = journal_lineDescLineNo.Default.(int)
	ledgerMixin := schema.Ledger{}.Mixin()
	ledgerMixinFields0 := ledgerMixin[0].Fields()
	_ = ledgerMixinFields0
	ledgerFields := schema.Ledger{}.Fields()
	_ = ledgerFields
	// ledgerDescStatus is the schema descriptor for status field.
	ledgerDescStatus := ledgerMixinFields0[0].Descriptor()
	// ledger.DefaultStatus holds the default value on creation for the status field.
	ledger.DefaultStatus = ledgerDescStatus.Default.(int8)
	// ledgerDescCreatedAt is the schema descriptor for created_at field.
	ledgerDescCreatedAt := ledgerMixinFields0[1].Descriptor()
	// ledger.DefaultCreatedAt holds the default value on creation for the created_at field.
	ledger.DefaultCreatedAt = ledgerDescCreatedAt.Default.(func() time.Time)
	// ledgerDescUpdatedAt is the schema descriptor for updated_at field.
	ledgerDescUpdatedAt := ledgerMixinFields0[2].Descriptor()
	// ledger.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ledger.DefaultUpdatedAt = ledgerDescUpdatedAt.Default.(func() time.Time)
	// ledger.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ledger.UpdateDefaultUpdatedAt = ledgerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ledgerDescCode is the schema descriptor for code field.
	ledgerDescCode := ledgerFields[1].Descriptor()
	// ledger.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	ledger.CodeValidator = ledgerDescCode.Validators[0].(func(string) error)
	// ledgerDescName is the schema descriptor for name field.
	ledgerDescName := ledgerFields[2].Descriptor()
	// ledger.NameValidator is a validator for the "name" field. It is called by the builders before save.
	ledger.NameValidator = func() func(string) error {
		validators := ledgerDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// ledgerDescAlias is the schema descriptor for alias field.
	ledgerDescAlias := ledgerFields[3].Descriptor()
	// ledger.DefaultAlias holds the default value on creation for the alias field.
	ledger.DefaultAlias = ledgerDescAlias.Default.(string)
	// ledger.AliasValidator is a validator for the "alias" field. It is called by the builders before save.
	ledger.AliasValidator = ledgerDescAlias.Validators[0].(func(string) error)
	// ledgerDescDescription is the schema descriptor for description field.
	ledgerDescDescription := ledgerFields[4].Descriptor()
	// ledger.DefaultDescription holds the default value on creation for the description field.
	ledger.DefaultDescription = ledgerDescDescription.Default.(string)
	// ledgerDescOpeningBalance is the schema descriptor for opening_balance field.
	ledgerDescOpeningBalance := ledgerFields[5].Descriptor()
	// ledger.DefaultOpeningBalance holds the default value on creation for the opening_balance field.
	ledger.DefaultOpeningBalance = ledgerDescOpeningBalance.Default.(float64)
	// ledgerDescBalance is the schema descriptor for balance field.
	ledgerDescBalance := ledgerFields[6].Descriptor()
	// ledger.DefaultBalance holds the default value on creation for the balance field.
	ledger.DefaultBalance = ledgerDescBalance.Default.(float64)
	// ledgerDescIsSystem is the schema descriptor for is_system field.
	ledgerDescIsSystem := ledgerFields[7].Descriptor()
	// ledger.DefaultIsSystem holds the default value on creation for the is_system field.
	ledger.DefaultIsSystem = ledgerDescIsSystem.Default.(bool)
	// ledgerDescIsParty is the schema descriptor for is_party field.
	ledgerDescIsParty := ledgerFields[8].Descriptor()
	// ledger.DefaultIsParty holds the default value on creation for the is_party field.
	ledger.DefaultIsParty = ledgerDescIsParty.Default.(bool)
	// ledgerDescIsBank is the schema descriptor for is_bank field.
	ledgerDescIsBank := ledgerFields[9].Descriptor()
	// ledger.DefaultIsBank holds the default value on creation for the is_bank field.
	ledger.DefaultIsBank = ledgerDescIsBank.Default.(bool)
	// ledgerDescIsCash is the schema descriptor for is_cash field.
	ledgerDescIsCash := ledgerFields[10].Descriptor()
	// ledger.DefaultIsCash holds the default value on creation for the is_cash field.
	ledger.DefaultIsCash = ledgerDescIsCash.Default.(bool)
	partymasterMixin := schema.PartyMaster{}.Mixin()
	partymasterMixinFields0 := partymasterMixin[0].Fields()
	_ = partymasterMixinFields0
	partymasterFields := schema.PartyMaster{}.Fields()
	_ = partymasterFields
	// partymasterDescStatus is the schema descriptor for status field.
	partymasterDescStatus := partymasterMixinFields0[0].Descriptor()
	// partymaster.DefaultStatus holds the default value on creation for the status field.
	partymaster.DefaultStatus = partymasterDescStatus.Default.(int8)
	// partymasterDescCreatedAt is the schema descriptor for created_at field.
	partymasterDescCreatedAt := partymasterMixinFields0[1].Descriptor()
	// partymaster.DefaultCreatedAt holds the default value on creation for the created_at field.
	partymaster.DefaultCreatedAt = partymasterDescCreatedAt.Default.(func() time.Time)
	// partymasterDescUpdatedAt is the schema descriptor for updated_at field.
	partymasterDescUpdatedAt := partymasterMixinFields0[2].Descriptor()
	// partymaster.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	partymaster.DefaultUpdatedAt = partymasterDescUpdatedAt.Default.(func() time.Time)
	// partymaster.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	partymaster.UpdateDefaultUpdatedAt = partymasterDescUpdatedAt.UpdateDefault.(func() time.Time)
	// partymasterDescDisplayName is the schema descriptor for display_name field.
	partymasterDescDisplayName := partymasterFields[2].Descriptor()
	// partymaster.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	partymaster.DisplayNameValidator = partymasterDescDisplayName.Validators[0].(func(string) error)
	// partymasterDescCreditLimit is the schema descriptor for credit_limit field.
	partymasterDescCreditLimit := partymasterFields[11].Descriptor()
	// partymaster.DefaultCreditLimit holds the default value on creation for the credit_limit field.
	partymaster.DefaultCreditLimit = partymasterDescCreditLimit.Default.(float64)
	// partymasterDescCreditDays is the schema descriptor for credit_days field.
	partymasterDescCreditDays := partymasterFields[12].Descriptor()
	// partymaster.DefaultCreditDays holds the default value on creation for the credit_days field.
	partymaster.DefaultCreditDays = partymasterDescCreditDays.Default.(int)
	// partymasterDescOpeningBalance is the schema descriptor for opening_balance field.
	partymasterDescOpeningBalance := partymasterFields[13].Descriptor()
	// partymaster.DefaultOpeningBalance holds the default value on creation for the opening_balance field.
	partymaster.DefaultOpeningBalance = partymasterDescOpeningBalance.Default.(float64)
	// partymasterDescCountry is the schema descriptor for country field.
	partymasterDescCountry := partymasterFields[17].Descriptor()
	// partymaster.DefaultCountry holds the default value on creation for the country field.
	partymaster.DefaultCountry = partymasterDescCountry.Default.(string)
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescKey is the schema descriptor for key field.
	settingDescKey := settingFields[0].Descriptor()
	// setting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	setting.KeyValidator = settingDescKey.Validators[0].(func(string) error)
	// settingDescValue is the schema descriptor for value field.
	settingDescValue := settingFields[1].Descriptor()
	// setting.DefaultValue holds the default value on creation for the value field.
	setting.DefaultValue = settingDescValue.Default.(string)
	// settingDescLabel is the schema descriptor for label field.
	settingDescLabel := settingFields[2].Descriptor()
	// setting.DefaultLabel holds the default value on creation for the label field.
	setting.DefaultLabel = settingDescLabel.Default.(string)
	// settingDescGroup is the schema descriptor for group field.
	settingDescGroup := settingFields[3].Descriptor()
	// setting.DefaultGroup holds the default value on creation for the group field.
	setting.DefaultGroup = settingDescGroup.Default.(string)
	stateFields := schema.State{}.Fields()
	_ = stateFields
	// stateDescName is the schema descriptor for name field.
	stateDescName := stateFields[0].Descriptor()
	// state.NameValidator is a validator for the "name" field. It is called by the builders before save.
	state.NameValidator = func() func(string) error {
		validators := stateDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// stateDescCode is the schema descriptor for code field.
	stateDescCode := stateFields[1].Descriptor()
	// state.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	state.CodeValidator = stateDescCode.Validators[0].(func(string) error)
	// stateDescGstCode is the schema descriptor for gst_code field.
	stateDescGstCode := stateFields[2].Descriptor()
	// state.GstCodeValidator is a validator for the "gst_code" field. It is called by the builders before save.
	state.GstCodeValidator = stateDescGstCode.Validators[0].(func(string) error)
}
