// Code generated by ent, DO NOT EDIT.

package journal_line

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the journal_line type in the database.
	Label = "journal_line"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldJournalID holds the string denoting the journal_id field in the database.
	FieldJournalID = "journal_id"
	// FieldLedgerID holds the string denoting the ledger_id field in the database.
	FieldLedgerID = "ledger_id"
	// FieldDebit holds the string denoting the debit field in the database.
	FieldDebit = "debit"
	// FieldCredit holds the string denoting the credit field in the database.
	FieldCredit = "credit"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldReferenceType holds the string denoting the reference_type field in the database.
	FieldReferenceType = "reference_type"
	// FieldReferenceID holds the string denoting the reference_id field in the database.
	FieldReferenceID = "reference_id"
	// FieldLineNo holds the string denoting the line_no field in the database.
	FieldLineNo = "line_no"
	// EdgeJournal holds the string denoting the journal edge name in mutations.
	EdgeJournal = "journal"
	// EdgeLedger holds the string denoting the ledger edge name in mutations.
	EdgeLedger = "ledger"
	// Table holds the table name of the journal_line in the database.
	Table = "journal_lines"
	// JournalTable is the table that holds the journal relation/edge.
	JournalTable = "journal_lines"
	// JournalInverseTable is the table name for the Journal entity.
	// It exists in this package in order to avoid circular dependency with the "journal" package.
	JournalInverseTable = "journals"
	// JournalColumn is the table column denoting the journal relation/edge.
	JournalColumn = "journal_id"
	// LedgerTable is the table that holds the ledger relation/edge.
	LedgerTable = "journal_lines"
	// LedgerInverseTable is the table name for the Ledger entity.
	// It exists in this package in order to avoid circular dependency with the "ledger" package.
	LedgerInverseTable = "ledgers"
	// LedgerColumn is the table column denoting the ledger relation/edge.
	LedgerColumn = "ledger_id"
)

// Columns holds all SQL columns for journal_line fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldJournalID,
	FieldLedgerID,
	FieldDebit,
	FieldCredit,
	FieldDescription,
	FieldReferenceType,
	FieldReferenceID,
	FieldLineNo,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "journal_lines"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"journal_lines",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int8
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDebit holds the default value on creation for the "debit" field.
	DefaultDebit float64
	// DefaultCredit holds the default value on creation for the "credit" field.
	DefaultCredit float64
	// DefaultLineNo holds the default value on creation for the "line_no" field.
	DefaultLineNo int
)

// OrderOption defines the ordering options for the Journal_Line queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByJournalID orders the results by the journal_id field.
func ByJournalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJournalID, opts...).ToFunc()
}

// ByLedgerID orders the results by the ledger_id field.
func ByLedgerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLedgerID, opts...).ToFunc()
}

// ByDebit orders the results by the debit field.
func ByDebit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDebit, opts...).ToFunc()
}

// ByCredit orders the results by the credit field.
func ByCredit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredit, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByReferenceType orders the results by the reference_type field.
func ByReferenceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferenceType, opts...).ToFunc()
}

// ByReferenceID orders the results by the reference_id field.
func ByReferenceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferenceID, opts...).ToFunc()
}

// ByLineNo orders the results by the line_no field.
func ByLineNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLineNo, opts...).ToFunc()
}

// ByJournalField orders the results by journal field.
func ByJournalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJournalStep(), sql.OrderByField(field, opts...))
	}
}

// ByLedgerField orders the results by ledger field.
func ByLedgerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLedgerStep(), sql.OrderByField(field, opts...))
	}
}
func newJournalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JournalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, JournalTable, JournalColumn),
	)
}
func newLedgerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LedgerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, LedgerTable, LedgerColumn),
	)
}
