// Code generated by ent, DO NOT EDIT.

package journal_line

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/subhasundardas/gofar/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldID, id))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int8) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldUpdatedAt, v))
}

// JournalID applies equality check predicate on the "journal_id" field. It's identical to JournalIDEQ.
func JournalID(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldJournalID, v))
}

// LedgerID applies equality check predicate on the "ledger_id" field. It's identical to LedgerIDEQ.
func LedgerID(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldLedgerID, v))
}

// Debit applies equality check predicate on the "debit" field. It's identical to DebitEQ.
func Debit(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldDebit, v))
}

// Credit applies equality check predicate on the "credit" field. It's identical to CreditEQ.
func Credit(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldCredit, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldDescription, v))
}

// ReferenceType applies equality check predicate on the "reference_type" field. It's identical to ReferenceTypeEQ.
func ReferenceType(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldReferenceType, v))
}

// ReferenceID applies equality check predicate on the "reference_id" field. It's identical to ReferenceIDEQ.
func ReferenceID(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldReferenceID, v))
}

// LineNo applies equality check predicate on the "line_no" field. It's identical to LineNoEQ.
func LineNo(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldLineNo, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int8) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int8) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int8) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int8) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int8) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int8) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int8) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int8) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldUpdatedAt, v))
}

// JournalIDEQ applies the EQ predicate on the "journal_id" field.
func JournalIDEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldJournalID, v))
}

// JournalIDNEQ applies the NEQ predicate on the "journal_id" field.
func JournalIDNEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldJournalID, v))
}

// JournalIDIn applies the In predicate on the "journal_id" field.
func JournalIDIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldJournalID, vs...))
}

// JournalIDNotIn applies the NotIn predicate on the "journal_id" field.
func JournalIDNotIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldJournalID, vs...))
}

// LedgerIDEQ applies the EQ predicate on the "ledger_id" field.
func LedgerIDEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldLedgerID, v))
}

// LedgerIDNEQ applies the NEQ predicate on the "ledger_id" field.
func LedgerIDNEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldLedgerID, v))
}

// LedgerIDIn applies the In predicate on the "ledger_id" field.
func LedgerIDIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldLedgerID, vs...))
}

// LedgerIDNotIn applies the NotIn predicate on the "ledger_id" field.
func LedgerIDNotIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldLedgerID, vs...))
}

// DebitEQ applies the EQ predicate on the "debit" field.
func DebitEQ(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldDebit, v))
}

// DebitNEQ applies the NEQ predicate on the "debit" field.
func DebitNEQ(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldDebit, v))
}

// DebitIn applies the In predicate on the "debit" field.
func DebitIn(vs ...float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldDebit, vs...))
}

// DebitNotIn applies the NotIn predicate on the "debit" field.
func DebitNotIn(vs ...float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldDebit, vs...))
}

// DebitGT applies the GT predicate on the "debit" field.
func DebitGT(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldDebit, v))
}

// DebitGTE applies the GTE predicate on the "debit" field.
func DebitGTE(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldDebit, v))
}

// DebitLT applies the LT predicate on the "debit" field.
func DebitLT(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldDebit, v))
}

// DebitLTE applies the LTE predicate on the "debit" field.
func DebitLTE(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldDebit, v))
}

// CreditEQ applies the EQ predicate on the "credit" field.
func CreditEQ(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldCredit, v))
}

// CreditNEQ applies the NEQ predicate on the "credit" field.
func CreditNEQ(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldCredit, v))
}

// CreditIn applies the In predicate on the "credit" field.
func CreditIn(vs ...float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldCredit, vs...))
}

// CreditNotIn applies the NotIn predicate on the "credit" field.
func CreditNotIn(vs ...float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldCredit, vs...))
}

// CreditGT applies the GT predicate on the "credit" field.
func CreditGT(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldCredit, v))
}

// CreditGTE applies the GTE predicate on the "credit" field.
func CreditGTE(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldCredit, v))
}

// CreditLT applies the LT predicate on the "credit" field.
func CreditLT(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldCredit, v))
}

// CreditLTE applies the LTE predicate on the "credit" field.
func CreditLTE(v float64) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldCredit, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldContainsFold(FieldDescription, v))
}

// ReferenceTypeEQ applies the EQ predicate on the "reference_type" field.
func ReferenceTypeEQ(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldReferenceType, v))
}

// ReferenceTypeNEQ applies the NEQ predicate on the "reference_type" field.
func ReferenceTypeNEQ(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldReferenceType, v))
}

// ReferenceTypeIn applies the In predicate on the "reference_type" field.
func ReferenceTypeIn(vs ...string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldReferenceType, vs...))
}

// ReferenceTypeNotIn applies the NotIn predicate on the "reference_type" field.
func ReferenceTypeNotIn(vs ...string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldReferenceType, vs...))
}

// ReferenceTypeGT applies the GT predicate on the "reference_type" field.
func ReferenceTypeGT(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldReferenceType, v))
}

// ReferenceTypeGTE applies the GTE predicate on the "reference_type" field.
func ReferenceTypeGTE(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldReferenceType, v))
}

// ReferenceTypeLT applies the LT predicate on the "reference_type" field.
func ReferenceTypeLT(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldReferenceType, v))
}

// ReferenceTypeLTE applies the LTE predicate on the "reference_type" field.
func ReferenceTypeLTE(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldReferenceType, v))
}

// ReferenceTypeContains applies the Contains predicate on the "reference_type" field.
func ReferenceTypeContains(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldContains(FieldReferenceType, v))
}

// ReferenceTypeHasPrefix applies the HasPrefix predicate on the "reference_type" field.
func ReferenceTypeHasPrefix(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldHasPrefix(FieldReferenceType, v))
}

// ReferenceTypeHasSuffix applies the HasSuffix predicate on the "reference_type" field.
func ReferenceTypeHasSuffix(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldHasSuffix(FieldReferenceType, v))
}

// ReferenceTypeIsNil applies the IsNil predicate on the "reference_type" field.
func ReferenceTypeIsNil() predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIsNull(FieldReferenceType))
}

// ReferenceTypeNotNil applies the NotNil predicate on the "reference_type" field.
func ReferenceTypeNotNil() predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotNull(FieldReferenceType))
}

// ReferenceTypeEqualFold applies the EqualFold predicate on the "reference_type" field.
func ReferenceTypeEqualFold(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEqualFold(FieldReferenceType, v))
}

// ReferenceTypeContainsFold applies the ContainsFold predicate on the "reference_type" field.
func ReferenceTypeContainsFold(v string) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldContainsFold(FieldReferenceType, v))
}

// ReferenceIDEQ applies the EQ predicate on the "reference_id" field.
func ReferenceIDEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldReferenceID, v))
}

// ReferenceIDNEQ applies the NEQ predicate on the "reference_id" field.
func ReferenceIDNEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldReferenceID, v))
}

// ReferenceIDIn applies the In predicate on the "reference_id" field.
func ReferenceIDIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldReferenceID, vs...))
}

// ReferenceIDNotIn applies the NotIn predicate on the "reference_id" field.
func ReferenceIDNotIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldReferenceID, vs...))
}

// ReferenceIDGT applies the GT predicate on the "reference_id" field.
func ReferenceIDGT(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldReferenceID, v))
}

// ReferenceIDGTE applies the GTE predicate on the "reference_id" field.
func ReferenceIDGTE(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldReferenceID, v))
}

// ReferenceIDLT applies the LT predicate on the "reference_id" field.
func ReferenceIDLT(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldReferenceID, v))
}

// ReferenceIDLTE applies the LTE predicate on the "reference_id" field.
func ReferenceIDLTE(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldReferenceID, v))
}

// ReferenceIDIsNil applies the IsNil predicate on the "reference_id" field.
func ReferenceIDIsNil() predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIsNull(FieldReferenceID))
}

// ReferenceIDNotNil applies the NotNil predicate on the "reference_id" field.
func ReferenceIDNotNil() predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotNull(FieldReferenceID))
}

// LineNoEQ applies the EQ predicate on the "line_no" field.
func LineNoEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldEQ(FieldLineNo, v))
}

// LineNoNEQ applies the NEQ predicate on the "line_no" field.
func LineNoNEQ(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNEQ(FieldLineNo, v))
}

// LineNoIn applies the In predicate on the "line_no" field.
func LineNoIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldIn(FieldLineNo, vs...))
}

// LineNoNotIn applies the NotIn predicate on the "line_no" field.
func LineNoNotIn(vs ...int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldNotIn(FieldLineNo, vs...))
}

// LineNoGT applies the GT predicate on the "line_no" field.
func LineNoGT(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGT(FieldLineNo, v))
}

// LineNoGTE applies the GTE predicate on the "line_no" field.
func LineNoGTE(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldGTE(FieldLineNo, v))
}

// LineNoLT applies the LT predicate on the "line_no" field.
func LineNoLT(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLT(FieldLineNo, v))
}

// LineNoLTE applies the LTE predicate on the "line_no" field.
func LineNoLTE(v int) predicate.Journal_Line {
	return predicate.Journal_Line(sql.FieldLTE(FieldLineNo, v))
}

// HasJournal applies the HasEdge predicate on the "journal" edge.
func HasJournal() predicate.Journal_Line {
	return predicate.Journal_Line(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, JournalTable, JournalColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJournalWith applies the HasEdge predicate on the "journal" edge with a given conditions (other predicates).
func HasJournalWith(preds ...predicate.Journal) predicate.Journal_Line {
	return predicate.Journal_Line(func(s *sql.Selector) {
		step := newJournalStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLedger applies the HasEdge predicate on the "ledger" edge.
func HasLedger() predicate.Journal_Line {
	return predicate.Journal_Line(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LedgerTable, LedgerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgerWith applies the HasEdge predicate on the "ledger" edge with a given conditions (other predicates).
func HasLedgerWith(preds ...predicate.Ledger) predicate.Journal_Line {
	return predicate.Journal_Line(func(s *sql.Selector) {
		step := newLedgerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Journal_Line) predicate.Journal_Line {
	return predicate.Journal_Line(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Journal_Line) predicate.Journal_Line {
	return predicate.Journal_Line(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Journal_Line) predicate.Journal_Line {
	return predicate.Journal_Line(sql.NotPredicates(p))
}
