// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Acct_Group is the predicate function for acct_group builders.
type Acct_Group func(*sql.Selector)

// Country is the predicate function for country builders.
type Country func(*sql.Selector)

// Journal is the predicate function for journal builders.
type Journal func(*sql.Selector)

// Journal_Line is the predicate function for journal_line builders.
type Journal_Line func(*sql.Selector)

// Ledger is the predicate function for ledger builders.
type Ledger func(*sql.Selector)

// PartyMaster is the predicate function for partymaster builders.
type PartyMaster func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// State is the predicate function for state builders.
type State func(*sql.Selector)
